spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.50:3306/coupon?useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: centos123qwer
      maxActive: 20
      initialSize: 3
      minIdle: 3
      validationQuery: select 1 from dual
      poolPreparedStatements: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      stat-view-servlet:
        loginUsername: root
        loginPassword: centos123qwer
        resetEnable: true
  jmx:
    enabled: false
  thymeleaf:
      cache: false
  redis:
      host: 192.168.1.50
      port: 6379
      password: centos123qwer
      database: 5
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1