package com.phoenix.core.exception;


import java.util.HashMap;
import java.util.Map;

public class ServiceMsg {
    public static final String SUCCESS = "1";
    public static final String FAIL = "0";
    public static final String SYS_ERROR = "9999";
    public static final String DB_ERROR = "9997";
    public static final String BIZ_ERROR = "9996";
    public static final String CACHE_ERROR = "9994";
    public static final String BIZ_HAD_DONE = "9993";
    public static final String OPER_TOO_FREQUENT = "9995";
    public static final String INTERFACE_ERROR = "9998";
    public static final String PARAM_ERROR = "9001";
    public static final String PARAM_NOT_DEFINE = "9002";
    public static final String METHOD_NOT_DEFINE = "9003";
    public static final String USER_LOGINED_TIMEOUT = "9004";
    public static final String USER_LOGINED_UNCHECKED = "9005";
    public static final String BIZ_NOT_SUPPORT = "9006";
    public static final String RECORD_NOT_FOUND = "9007";
    public static final String PARAM_EMPTY = "9008";
    public static final String PLT_FRONT_ERROR = "9009";
    public static final String PLT_FRONT_URL_ERROR = "9010";
    public static final String SYS_CONFIG_GET_ERROR = "9011";
    public static final String _ORDER_CENTER_LJ_ERROR = "9100";
    public static final String DATA_ERROR = "9110";
    public static final String SCHEDULE_FULL = "0001";
    public static final String SCHEDULE_STOP = "0003";
    public static final String PATIENT_IS_NOT_REG = "0002";
    public static final String HOSCODE_IS_INVALID = "1000";
    public static final String IDNO_IS_NULL = "1001";
    public static final String IDNO_FORMAT_ERROR = "1002";
    public static final String IDNO_ISNOT_REG = "1003";
    public static final String PHONENO_IS_NULL = "1004";
    public static final String PHONENO_FORMAT_ERROR = "1005";
    public static final String IDNO_IS_REG = "1006";
    public static final String PHONENO_BIND_LIMITED = "1007";
    public static final String NAME_IS_NULL = "1008";
    public static final String PWD_IS_NULL = "1009";
    public static final String PWD_IS_SHORT = "1010";
    public static final String VCODE_IS_NULL = "1011";
    public static final String VCODE_IS_SHORT = "1012";
    public static final String VCODE_IS_INVALID = "1013";
    public static final String USERID_EXISIT = "1014";
    public static final String VCODE_IS_OUTOFTIME = "1015";
    public static final String USER_IDNO_PHONE_IS_NULL = "1016";
    public static final String VCODE_NUMBER_IS_LIMITED = "1017";
    public static final String USER_IDNO_IS_NULL = "1018";
    public static final String NEWPWD_IS_NULL = "1019";
    public static final String NEWPWD_IS_SHORT = "1020";
    public static final String USER_IDNO_ISNOT_REG = "1021";
    public static final String USERID_PWD_ERROR = "1022";
    public static final String BIZTYPE_IS_NULL = "1023";
    public static final String BIZTYPE_UNKNOW = "1024";
    public static final String USER_PHONE_IS_NULL = "1025";
    public static final String USER_PHONE_FORMAT_ERROR = "1026";
    public static final String NO_FIND_CARD = "1027";
    public static final String PATIENTID_IS_NULL = "1028";
    public static final String SEARCHTYPE_IS_NULL = "1029";
    public static final String SEARCHPARAMS_IS_NULL = "1030";
    public static final String BAIDU_CHANNELID_IS_NULL = "1031";
    public static final String BAIDU_USERID_IS_NULL = "1032";
    public static final String USER_IS_DULIP = "1033";
    public static final String NO_SUPPORT_PAYMENT = "1034";
    public static final String PATIENT_IDNO_IS_CHILD = "1035";
    public static final String NO_SUPPORT_QUEUE = "1036";
    public static final String NO_REACH_DOCTOR_WORK_TIME = "1037";
    public static final String CHECK_ERROR = "1038";
    public static final String UPDAT_CARD_ERROR = "1039";
    public static final String CRAD_MULIT = "1040";
    public static final String CARD_NUM_ERROR = "1041";
    public static final String REG_ERROR_BUT_REFUND_SUCCESS = "1042";
    public static final String PAY_SUCCESS = "1043";
    public static final String NO_SUPPORT_PAY = "1044";
    public static final String PAYMETHOD_IS_WRONG = "1045";
    public static final String NO_SUPPORT_QUERY_PRENO = "1046";
    public static final String NO_SUPPORT_YB = "1047";
    public static final String CANNOT_ADD_YOURSELF_TO_COMMUSER = "1048";
    public static final String DATA_EMPTY = "1049";
    public static final String OVER_LIMIT_COMMUSER_NUM = "1050";
    public static final String PAY_ERROR = "1051";
    public static final String NO_FIND_PREREGISTER_CONFIRM_INFO = "1052";
    public static final String NAME_FORMATE_ERROR = "1053";
    public static final String NAME_WITHD_12320_DIFFER = "1054";
    public static final String TPORDUCT_ID_IS_NULL = "1055";
    public static final String NO_SUPPORT_CARDTYPE = "1056";
    public static final String PRENOS_NOT_FOUND = "1057";
    public static final String BIZ_IS_DOING = "1058";
    public static final String SI_SUMMARY_FAIL = "1059";
    public static final String CARD_NO_IS_NULL = "1060";
    public static final String DEPT_LIMIT_SEX = "1091";
    public static final String CARD_NO_IS_NOT_ENOUGH = "1201";
    public static final String CARD_NO_TYPE_IS_NULL = "1061";
    public static final String SI_PAY_IS_NOT_OPEN = "1062";
    public static final String NO_OPEN_PREREG_CONFRIM_FUN = "1063";
    public static final String NO_ORDER_FOUND = "1064";
    public static final String ORDER_IS_DONE = "1065";
    public static final String REPORT_PATIENT_NAME_ERROR = "1066";
    public static final String FRIST_VISIT_CANNOT_PAY = "1067";
    public static final String PHONE_REFEREE_ERROR = "1068";
    public static final String VCODE_IS_FAIL = "1069";
    public static final String DATE_FORMAT_ERROR = "1070";
    public static final String _PHONE_ISREGISTER_ERROR = "1071";
    public static final String _USERLOG_REDIS_ERROR = "1072";
    public static final String _SAVE_REDIS_ERROR = "1073";
    public static final String _USER_INFO_ERROR = "1074";
    public static final String _USER_PHONE_ERROR = "1075";
    public static final String SCHEDUE_IS_FULL = "1076";
    public static final String RECHARGE_AMT_OUTOF_LIMIT = "1077";
    public static final String TP_PAY_SIGN_ERROR = "1078";
    public static final String SI_SUMMARY_NOTSI = "1079";
    public static final String SI_PERSON_EMPTY = "1080";
    public static final String CHANNEL_CODE_EMPTY = "1081";
    public static final String _SI_REGISTERCONFIRM_ERROR = "1082";
    public static final String _REGISTERCOMFIRM_ERROR = "1083";
    public static final String _SI_REFUND_ERROR = "1084";
    public static final String _USERNAME_SAME_ERROR = "1085";
    public static final String _USERNAME_UPDATE_ERROR = "1086";
    public static final String _USERNAME_NOT_MATE = "1089";
    public static final String SI_PAY_NOT_REALNAME = "1090";
    public static final String _USER_SBK_MATCH_ERROR = "1087";
    public static final String _USER_YBK_MATCH_ERROR = "1088";
    public static final String _IS_ACCOUNT_ERROR = "1099";
    public static final String _NOT_ACCOUNT_ERROR = "1100";
    public static final String _LOGIN_PWD_ERROR = "1101";
    public static final String _ORI_PWD_ERROR = "1102";
    public static final String _PWD_EQ_ERROR = "1103";
    public static final String _PWD_ERROR = "1104";
    public static final String _EMAIL_FORMAT_ERROR = "1200";
    public static final String JSNJ_12320_ERROR = "2000";
    public static final String _12320_CALL_ERROR = "2001";
    public static final String _12320_LOGIN_ERROR = "2002";
    public static final String _12320_REGISTER_ERROR = "2003";
    public static final String _12320_XG_ERROR = "2004";
    public static final String _PHONE_SAME_ERROR = "2005";
    public static final String _12320_R_ERROR = "2006";
    public static final String _PK12320_ACCOUNT_REQUIRE_ERROR = "2007";
    public static final String _PK12320_ACCOUNT_ERROR = "2008";
    public static final String _PK123220_ERROR = "2009";
    public static final String _MYNANJING_ID_ERROR = "3000";
    public static final String _MYNANJING_SESSION_ERROR = "3001";
    public static final String _CACHE_DOC_ERROR = "8001";
    public static final String _OPER_ERROR = "8002";
    public static final String _ADD_PRAISE_ERROR = "8003";
    public static final String _MSG_CENTER_LJ_ERROR = "9000";
    public static final String _AUTH_AUTHCODE_ISNULL_ERROR = "3101";
    public static final String _AUTH_OPENID_ISNULL_ERROR = "3102";
    public static final String _AUTH_TOKEN_ERROR = "3103";
    public static final String _AUTH_USR_ERROR = "3104";
    public static final String _AUTH_AUTHCODE_ERROR = "3201";
    public static final String USER_ID_IS_NULL = "1105";
    public static final String USER_STATE_PICURL_IS_NULL = "1106";
    public static final String _NJSI_SERVICE_ERROR = "7101";
    public static final String _NJGCNHSI_SERVIER_ERROR = "7201";
    public static final String _NULL_ERROR = "9199";
    public static final String TERMINAL_CODE_NULL_ERROR = "9198";
    public static final String INTERFACE_STOP = "9197";
    private static HashMap<String, String> msg_Container = new HashMap();

    static {
        msg_Container.put("1", "成功响应");
        msg_Container.put("0", "操作失败！");
        msg_Container.put("9999", "系统错误");
        msg_Container.put("9997", "调用数据库错误");
        msg_Container.put("9994", "缓存异常");
        msg_Container.put("9993", "不可重复操作");
        msg_Container.put("9995", "操作过频繁，稍后再试");
        msg_Container.put("9996", "业务失败");
        msg_Container.put("9001", "参数错误");
        msg_Container.put("9002", "参数未定义");
        msg_Container.put("9003", "方法未定义");
        msg_Container.put("9004", "登录状态失效");
        msg_Container.put("9005", "亲，请重新登录");
        msg_Container.put("9006", "暂不支持该业务");
        msg_Container.put("9007", "记录不存在");
        msg_Container.put("9008", "参数为空");
        msg_Container.put("9009", "院端异常");
        msg_Container.put("9010", "院端请求地址未定义");
        msg_Container.put("9011", "系统配置获取失败");
        msg_Container.put("0001", "号源已满");
        msg_Container.put("0002", "病人未注册");
        msg_Container.put("1000", "医院编码为空或不合法");
        msg_Container.put("1001", "身份证号为空");
        msg_Container.put("1002", "身份证号格式错误");
        msg_Container.put("1003", "身份证未注册");
        msg_Container.put("1004", "手机号码为空");
        msg_Container.put("1005", "手机号码格式错误");
        msg_Container.put("1079", "医保试算失败:非医保项目，请至人工窗口。");
        msg_Container.put("1080", "医保人员信息查询失败");
        msg_Container.put("1006", "该信息已登记，请不要重复登记");
        msg_Container.put("1007", "手机号码与身份证绑定数量已达到最大限额");
        msg_Container.put("1008", "用户姓名为空");
        msg_Container.put("1009", "登录密码为空");
        msg_Container.put("1010", "登录密码少于6个字符");
        msg_Container.put("1011", "验证码为空");
        msg_Container.put("1012", "验证码不足6位");
        msg_Container.put("1013", "验证码校验错误");
        msg_Container.put("1014", "用户ID已存在");
        msg_Container.put("1015", "验证码已失效，请重新获取");
        msg_Container.put("1016", "用户ID/身份证号或手机号码不能为空");
        msg_Container.put("1017", "已超过系统对单日内同一手机号码的短信发送次数上限");
        msg_Container.put("1018", "用户ID/身份证号为空");
        msg_Container.put("1019", "重置密码为空");
        msg_Container.put("1020", "重置密码少于6个字符");
        msg_Container.put("1021", "用户ID/身份证号未注册");
        msg_Container.put("1022", "账号或密码错误，请重新输入");
        msg_Container.put("1023", "业务类型为空");
        msg_Container.put("1024", "业务类型未知");
        msg_Container.put("1025", "用户注册的电话号码为空");
        msg_Container.put("1026", "用户注册的电话号码格式错误");
        msg_Container.put("1027", "未查询到就诊卡");
        msg_Container.put("2000", "12320错误");
        msg_Container.put("1028", "常用就诊人身份证号为空");
        msg_Container.put("1029", "查询类别为空");
        msg_Container.put("1030", "查询条件为空");
        msg_Container.put("1031", "百度推送channelId为空");
        msg_Container.put("1032", "百度推送userId为空");
        msg_Container.put("1033", "该就诊人已添加,不可重复添加");
        msg_Container.put("1034", "暂不支持划价单缴费");
        msg_Container.put("1035", "用户未成年，请重新输入或输入监护人身份证");
        msg_Container.put("1036", "暂不支持排队叫号查询");
        msg_Container.put("1037", "当前时间无医生坐诊，暂无排队信息");
        msg_Container.put("1038", "就诊卡号医院验证未通过");
        msg_Container.put("1039", "更新就诊卡信息失败");
        msg_Container.put("1040", "卡号重复");
        msg_Container.put("1041", "卡号长度错误(12位或16位)");
        msg_Container.put("1201", "卡号长度错误(8位或18位)");
        msg_Container.put("1042", "挂号失败,已为您自动退费");
        msg_Container.put("1043", "请您稍后查询\"我的就诊\"，并以短信通知为准");
        msg_Container.put("1044", "暂不支持支付");
        msg_Container.put("1045", "支付方式错误");
        msg_Container.put("1046", "暂不支持划价单查询");
        msg_Container.put("1047", "该院暂不支持医保");
        msg_Container.put("1048", "不可添加自己为常用就诊人");
        msg_Container.put("1049", "暂无数据");
        msg_Container.put("1050", "已达常用就诊人最大添加人数");
        msg_Container.put("1051", "订单未支付");
        msg_Container.put("1052", "未查询到有效预约记录");
        msg_Container.put("1053", "姓名格式错误");
        msg_Container.put("1054", "姓名与12320账户不一致");
        msg_Container.put("1055", "产品编码不能为空");
        msg_Container.put("1056", "暂不支持该卡类型");
        msg_Container.put("1057", "划价单已失效，请刷新再试下");
        msg_Container.put("1058", "业务处理中,请稍后");
        msg_Container.put("1059", "医保试算失败");
        msg_Container.put("1060", "就诊卡号为空");
        msg_Container.put("1061", "就诊卡类型为空");
        msg_Container.put("1062", "此卡未开通在线支付");
        msg_Container.put("1063", "暂未开通预约取号功能");
        msg_Container.put("1064", "未找到订单");
        msg_Container.put("1065", "订单已处理");
        msg_Container.put("1066", "就诊人信息与报告单信息不一致，请确认");
        msg_Container.put("1067", "您暂未在院内完成就诊卡注册，本次暂不能使用在线挂号服务");
        msg_Container.put("1069", "验证码发送失败！");
        msg_Container.put("1070", "日期格式错误！");
        msg_Container.put("1068", "该手机号已生成过推荐码！");
        msg_Container.put("1071", "该手机号已经被注册过了！");
        msg_Container.put("1072", "登录用户缓存数据失败！");
        msg_Container.put("1073", "缓存用户数据失败！");
        msg_Container.put("1074", "用户信息为空！");
        msg_Container.put("1075", "手机号码未变更！");
        msg_Container.put("2001", "12320注册失败！");
        msg_Container.put("2003", "南京12320注册失败！");
        msg_Container.put("2004", "南京12320修改用户信息失败！");
        msg_Container.put("2005", "修改手机号与原手机号相同!");
        msg_Container.put("1076", "号源已满");
        msg_Container.put("1077", "充值金额超限");
        msg_Container.put("1078", "第三方支付下单失败");
        msg_Container.put("3000", "我的南京sessionid不能为空");
        msg_Container.put("3001", "获取我的南京session失败");
        msg_Container.put("2007", "身份证号和密码必填");
        msg_Container.put("2008", "账号信息错误，获取失败");
        msg_Container.put("2009", "12320接口服务失败！");
        msg_Container.put("1099", "已存在该账号信息");
        msg_Container.put("1100", "不存在该账号信息");
        msg_Container.put("1101", "密码错误次数已达上限");
        msg_Container.put("1102", "原密码不能为空!");
        msg_Container.put("1103", "原密码与修改密码相同！");
        msg_Container.put("1104", "密码错误！");
        msg_Container.put("9000", "消息中心hessian连接错误!");
        msg_Container.put("8001", "获取缓存中的医生信息错误");
        msg_Container.put("8002", "没有操作权限");
        msg_Container.put("8003", "已点赞");
        msg_Container.put("9998", "网络接口调用异常！");
        msg_Container.put("9110", "网络接口数据处理异常！");
        msg_Container.put("1200", "电子邮箱格式错误");
        msg_Container.put("1105", "用户ID为空！");
        msg_Container.put("1106", "用户申述图片为空！");
        msg_Container.put("7101", "调用南京医保服务失败,请重新调用");
        msg_Container.put("7201", "调用南京高淳农合医保失败，请重新调用");
        msg_Container.put("9100", "调用订单中心连接错误！");
        msg_Container.put("1082", "医保结算失败！");
        msg_Container.put("1083", "挂号失败！");
        msg_Container.put("1084", "医保退费失败");
        msg_Container.put("1085", "用户名未变更");
        msg_Container.put("1086", "更新用户名失败");
        msg_Container.put("1090", "无法进行医保结算，请先开通实名认证。");
        msg_Container.put("9199", "传入空对象");
        msg_Container.put("3101", "第三方授权码不能为空！");
        msg_Container.put("3102", "第三方openId不能为空！");
        msg_Container.put("3103", "获取第三方平台令牌token错误！");
        msg_Container.put("3104", "获取第三方用户信息失败");
        msg_Container.put("3201", "第三方授权码错误");
        msg_Container.put("1087", "当前账户身份信息与该就诊卡院内注册信息不符，请核实或在院内人工窗口更新就诊卡信息！");
        msg_Container.put("1088", "当前账户身份信息与该就诊卡医保中心注册信息不符，请核实！");
        msg_Container.put("1091", "该科室限定就诊人性别！");
        msg_Container.put("9198", "终端号为空!");
        msg_Container.put("9197", "接口停用");
    }

    public ServiceMsg() {
    }

    public static String getRspMsg(String rspCode) {
        return (String)msg_Container.get(rspCode);
    }

    public static String getJsonRspMsg(String rspCode) {
        return "{\"rspCode\":\"" + rspCode + "\",\"rspMsg\":\"" + getRspMsg(rspCode) + "\"}";
    }

    public static Map<String, Object> getRspMsgMap(String rspCode) {
        Map<String, Object> mapper = new HashMap();
        mapper.put("rspCode", rspCode);
        mapper.put("rspMsg", getRspMsg(rspCode));
        return mapper;
    }
}
